[versions]
activityCompose = "1.12.2"
agp = "8.13.2"
androidxComposeBom = "2025.12.01"
cardview = "1.0.0"
coil = "2.6.0"
composeBom = "2025.06.01"
composeBomVersion = "2024.10.00"
evervaultCore = "1.2"
evervaultEnclaves = "1.13.1"
kotlin = "2.0.21"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
lifecycleViewmodelKtx = "2.9.1"
material = "1.12.0"
materialVersion = "1.11.0"
mockwebserver = "5.1.0"
mockwebserverVersion = "4.12.0"
okhttp = "4.12.0"
gson = "2.11.0"
recyclerview = "1.4.0"
recyclerviewVersion = "1.3.2"
material3Android = "1.3.2"
robolectric = "4.15.1"
securityCrypto = "1.1.0"
securityCryptoVersion = "1.1.0-alpha06"
siftAndroid = "1.3.0"
cameraX = "1.3.3"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-bom-v20241000 = { module = "androidx.compose:compose-bom", version.ref = "composeBomVersion" }
androidx-compose-bom-v20251201 = { module = "androidx.compose:compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-material = { module = "androidx.compose.material:material" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-recyclerview-v132 = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerviewVersion" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
androidx-security-crypto-v110alpha06 = { module = "androidx.security:security-crypto", version.ref = "securityCryptoVersion" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
evervault-core = { module = "com.evervault.sdk:evervault-core", version.ref = "evervaultCore" }
evervault-enclaves = { module = "com.evervault.sdk:evervault-enclaves", version.ref = "evervaultEnclaves" }
evervault-inputs = { module = "com.evervault.sdk:evervault-inputs", version.ref = "evervaultEnclaves" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
material-v1110 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockwebserver" }
mockwebserver-v4120 = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockwebserverVersion" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
sift-android = { module = "com.siftscience:sift-android", version.ref = "siftAndroid" }
ui = { module = "androidx.compose.ui:ui" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "cameraX" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraX" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraX" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraX" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

